#!/usr/bin/env bash
# graph/graphify-lock.sh [<version> [<extras>]]
#
# Prints the hashed pip lock the graphify image installs from
# (graph/graphify-requirements.txt): graphifyy <version> with the
# comma-separated pip <extras> and every dependency, pinned to an exact
# version with sha256 hashes, resolved for the image's Python on x86_64
# Linux. Needs uv. The defaults are the lock's current spec, so to bump:
#   graph/graphify-lock.sh <new version> [<extras>] > graph/graphify-requirements.txt.new
#   mv graph/graphify-requirements.txt.new graph/graphify-requirements.txt
# The next ct graph build rebuilds the image (its tag hashes the lock).
set -euo pipefail
lock="$(dirname "$0")/graphify-requirements.txt"
current="$(sed -n 's/^# spec: //p' "$lock")"
python="$(sed -n 's/^# python: \([0-9.]*\) .*/\1/p' "$lock")"
cur_extras="${current#*[}"; cur_extras="${cur_extras%%]*}"
version="${1:-${current##*==}}"
extras="${2:-$cur_extras}"
spec="graphifyy[$extras]==$version"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
echo "$spec" > "$tmp/requirements.in"

echo "# spec: $spec"
echo "# python: $python x86_64-unknown-linux-gnu"
echo "# Generated by graph/graphify-lock.sh (see UPDATES.md); don't edit by hand."
uv pip compile "$tmp/requirements.in" \
  --python-version "$python" \
  --python-platform x86_64-unknown-linux-gnu \
  --generate-hashes \
  --no-header \
  | sed "s|$tmp/requirements.in|$spec|"
