package scaffold

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
)

// HistoryComment heads assets/scaffold-history.json.
const HistoryComment = "sha256 of every version of each file ct has shipped into vaults, over content normalized to LF line endings and one trailing newline. From the git history of assets/vault-scaffold/ (tools/vault-scaffold/ before 98caa68). Generated by go generate ./assets, never edited by hand; hashes are only ever added."

type historyFile struct {
	Comment string              `json:"_comment"`
	Files   map[string][]string `json:"files"`
}

// ParseHistory reads a history file: rel → hashes.
func ParseHistory(data []byte) (map[string][]string, error) {
	var h historyFile
	if err := json.Unmarshal(data, &h); err != nil {
		return nil, err
	}
	if h.Files == nil {
		h.Files = map[string][]string{}
	}
	return h.Files, nil
}

// FormatHistory writes a history file: paths sorted, each one's hashes
// sorted and unique, ending with a newline.
func FormatHistory(files map[string][]string) ([]byte, error) {
	clean := map[string][]string{}
	for rel, hashes := range files {
		seen := map[string]bool{}
		var list []string
		for _, h := range hashes {
			if !seen[h] {
				seen[h] = true
				list = append(list, h)
			}
		}
		sort.Strings(list)
		clean[rel] = list
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(historyFile{Comment: HistoryComment, Files: clean}); err != nil {
		return nil, fmt.Errorf("history: %w", err)
	}
	return buf.Bytes(), nil
}
